# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shch-recipes-api

on:
  push:
    branches:
      - release/0.1.1
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://shrecipes.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4f4265ac19cd4b6d8458efa979266309 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_06ae2f4525264e07b2654182e03db085 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: shrecipes.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4f4265ac19cd4b6d8458efa979266309 }}/recipes-api:${{ github.sha }}
        file: ./recipes/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shch-recipes-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5714e69dd6264778b8a300001cc068b5 }}
        images: 'shrecipes.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4f4265ac19cd4b6d8458efa979266309 }}/recipes-api:${{ github.sha }}'
